name: Zip and Upload Folder

on:
  push:
    branches:
      - test-wordpress-playground  # Change this to your default branch

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Zip Folder
      run: |
        cd web/app/themes/
        zip -r solidarityknowsnoborders.zip solidarityknowsnoborders

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: solidarityknowsnoborders
        path: web/app/themes/solidarityknowsnoborders.zip
